steps:
  - name: "reactnativecommunity/react-native-android"
    entrypoint: bash
    args:
      - "-c"
      - >
        npm install
    id: "Execute: npm install"

  - name: "reactnativecommunity/react-native-android"
    entrypoint: bash
    args:
      - "-c"
      - >
        npm run lint
    id: "Execute: npm run lint"

  - name: "reactnativecommunity/react-native-android"
    entrypoint: bash
    args:
      - "-c"
      - >
        npm run test
    id: "Execute: npm test"

  - name: "reactnativecommunity/react-native-android"
    entrypoint: bash
    args:
      - "-c"
      - >
        cd android &&
        chmod +x gradlew &&
        ./gradlew assembleRelease
    id: "build application"
